### ISSUE TITLE
Racers with empty names have incorrect lap data

### ISSUE THREAD

**Issue by cchalm** [thomasesmith/kartlaps#6]
https://kartlaps.info/v2/tirwashington/heat/50628

If you look at the laps recorded for the three empty-named racers in the above heat, there's something not quite right. There are too many laps for each empty-named racer, and there are multiple first laps, multiple second laps, etc, in a single racer's list. It looks like each empty-named racer's laps is the combination of all the named racers' laps.

The data on the source clubspeed page seems correct.

Both v1 and v2 have this oddity.

**Comment by thomasesmith** [comment]
This may be a tough one to fix. But I can see why this is happening.

This happens because the API is forced to use the string value of each racer's name to collect their individual laps further down the page, rather than using something unique like their racer id number. I can't use their racer id number to collect their lap data for that heat, because Club Speed's html markup doesn't use the racer id in the lap times area of the page. It only uses the racer names that participated in the heat. So, since there are three racers in this example heat you've shown with what amount to the same racer name (""), it's going to collect the laps for the racer name, assume that all three sets of laps belong to each of them, and add each lap to each of their lap sets. So all three racers will show to have run all three lap sets. This would happen the same way if there were any two or more racers in a heat that had the same exact string as their racer name. So, this problem is much more far-reaching than this one heat.

I am going to have to try and think of a better way to gather each racer's lap information that doesn't rely on the racer's name alone. 

Keep this one open. Thanks.

**Comment by cchalm** [comment]
It looks like the \<td\> tags in the html's LapTimeContainer (xpath /body/form/table/tbody/tr[6]/td/table/tbody/tr/td) are ordered by racer IDs. So if you know the IDs of all participants, the first \<td\> is guaranteed to belong to the racer with the smallest ID, and so on.

Wow the site's html is disorganized. Tables everywhere

**Comment by thomasesmith** [comment]
Wow, good catch. You're right. I've checked a few heats and the Heat page does always seem to list lap sets in order of racer id! I can implement the fix this way. It's an unsafe assumption of course, to plan on Club Speed's output to ever be consistent, but not anymore unsafe than the rest of the assumptions this API makes about their output :) This will work. 

And yeah, their html is a real flashback; malformed and non-semantic. I can see why some of this data actually might benefit from the use of table elements, because much of it *is* actually tabular, but they also use table elements for visual design. _The dream of the '90s is alive!_

Thanks!

**Comment by thomasesmith** [comment]
I have put the new code for this in production. Thanks @cchalm. Let me know if you find it behaving strangely at all.
