### ISSUE TITLE
Heat available in v1 API but not v2

### ISSUE THREAD

**Issue by cchalm** [thomasesmith/kartlaps#9]
The v2 api returns that heat 58555 is not available (as of 6pm PST)
http://kartlaps.info/v2/tirwashington/heat/58555

While this link shows that it is:
http://tirwashington.clubspeedtiming.com/sp_center/HeatDetails.aspx?HeatNo=58555

The heat is also available via the v1 api:
http://kartlaps.info/tirwashington/heat/58555

Similar results with 58557. This might not be a bug if you're batching and caching queries on some schedule, or something like that, but I thought I'd bring it to your attention in case it is unexpected

**Comment by thomasesmith** [comment]
That /v2 address you used as an example does now show the data for the heat when I check it. But I understand that it's now nearly 20 hours since you posted this issue. 

Does your client happen to try and grab new heat data perpetually as it happens, by incrementing up the heat id sequence automatically? Just curious. Because...

The /v2 API (as it is configured right now in production) only goes to scrape something if its asked to by a request (i.e. by you). If a heat id is submitted to it and it finds no data there to scrape, it reports that it found no heat in the JSON output (what you saw), but because it made a request to Club Speed servers to do so, it also cached the response it got from the CS server, and it holds on to that for 8 minutes. If you were to request the /v2 url again less than 8 minutes later, you'd be getting a response based on that cache it had, not one based on the live information found at the Club Speed url. After 8 minutes, that cache would expire and a request would behave normally. Do you consider this to be reasonable, seeing as how heats tend to take about 10 minutes to complete anyway? 

What this does bring to my attention however, is that the "recoveredFromCache" value outputted in each request is not reporting that status accurately. I added it there so clients could have some indication of why something like this happened, but testing it now I see that it keeps spitting out a perpetual "false" even when I can see that it should be "true." So I will fix that. 

Note also that the /v1 caching works differently than that of /v2, so I am not alarmed that they behave differently here.

**Comment by thomasesmith** [comment]
I have fixed the issue in production that was causing recoveredFromCache flag to not be raised in the event of a cache-based response. Small mistake on my part.

But please let me know if you think my caching routine/timing is faulty for your use-case, @cchalm. Thanks

**Comment by cchalm** [comment]
That's exactly what I do, and that sounds like a reasonable explanation.

I don't think I made the query every eight minutes from the start of my debugging though. And I only started debugging after doing a few scans for new heats many hours apart and discovering no new data, which makes me think maybe the cache was hanging on for longer than eight minutes. I don't have concrete data for that though. I'll open a new issue if necessary. This one is good to close. Thanks!
